spring.application.name=share-mate

spring.datasource.url=jdbc:postgresql://localhost:5432/sharemate
spring.datasource.password=postgres
spring.datasource.username=postgres

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
